### ISSUE TITLE
Error Loading dataset

### ISSUE THREAD

**Issue by ghost** [thinline72/nsl-kdd#3]
i'm using python 3.6, and cloned the repository when try to run kernel, i got error on load_dataset function.

**Comment by thinline72** [comment]
Hi @rezaagungp,

Could you provide error stacktrace, please?

**Comment by abirnedia** [comment]
Error with label_mapping_model #4 could you help me plz!

**Comment by aiyanzidexiaotao** [comment]
# Loading train data
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
